### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by H-Stein** [JGCRISummer2024/Global-Scale-Birch-Effect#1]
- [x] Explore the srdb data (time range, distributions of respiration numbers)
- [x] Make a nicer world map (continent outlines (ggmap / google))
- [x] investigate the SPEI data set (use R package that goes with it), time scale, spatial resolution
- [x] find out why the color scale was so weird (filter out insane values)
- [x] for a given lat, long, time point, pull out the drought index from SPEI
- [ ] bring srdb and spei together

**Comment by bpbond** [comment]
White board from today, in case useful as a reference. 

![image](https://github.com/JGCRISummer2024/CO2-variability-with-droughts/assets/1956468/c81487e4-4067-47f7-a8f8-45497413738d)

**Comment by bpbond** [comment]
- [x] Use the `spatialdata` repo as a model for bringing in SPEI data
- [x] Investigate the different SPEI indices (feel free to assign me reading as well!) Ideally they have an annual product that we will link up with SRDB data
- [x] If we end up using monthly, want to think/do research about what to use (average? Max? ...?) -> in this case, there will be a "compute annual value" step resulting in {site, year, value}
- [ ] Once SPEI is merged (will be based on location AND time) with SRDB data, make some maps!


Bonus time:

- [ ] The spatialdata repo also has a WorldClim example, which we will want at some point: climatology (average conditions) for each site
